resources:
  - name: {{ .Values.Resource1.name }}
    type: Image
    configuration:
      registry: {{ .Values.Artifactory }}
      sourceRepository: docker
      imageName: {{ .Values.Resource1.imageName }}
      imageTag: '${run_number}'
      autoPull: true
  - name: {{ .Values.Resource2.name }}
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.Artifactory }}
      buildName: {{ .Values.Pipelines.name }}
      buildNumber: 1
  - name: {{ .Values.Resource3.name }}
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.Resource3.gitProvider }}
      path: {{ .Values.Resource3.path }}
      branches:
        include: {{ .Values.Resource3.branch }}

pipelines:
  - name: {{ .Values.Pipelines.name }}
    steps:
      - name: {{ .Values.Step1.name }}
        type: MvnBuild
        configuration:
          sourceLocation: {{ .Values.GitRepo.path }}
          mvnCommand: clean install -ntp
          environmentVariables:
            JFROG_CLI_BUILD_NAME: backend-build
          resolverSnapshotRepo: libs-snapshot-virtual
          resolverReleaseRepo: libs-staging-virtual  
          deployerSnapshotRepo: libs-snapshot-local
          deployerReleaseRepo: libs-staging-local
          inputResources:
            - name: {{ .Values.GitRepo.name }}
          integrations:
            - name: {{ .Values.Artifactory }}
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
          onComplete:
            - echo $run_var
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
          onSuccess:
            - rm -r ${steplet_run_state_dir}/jfrog
      
      - name: {{ .Values.Step2.name }}
        type: DockerBuild
        configuration:
          affinityGroup: bldGroup
          dockerFileLocation: {{ .Values.Step2.dockerFileLocation }}
          dockerFileName: Dockerfile
          dockerImageName: {{ .Values.Step2.dockerImageName }}
          dockerImageTag: '${run_number}'
          integrations:
            - name: {{ .Values.Artifactory }}
          inputResources:
            - name: {{ .Values.GitRepo.name }}
              trigger: false
          outputResources:
            - name: {{ .Values.Step2.outputResourceName }}
          inputSteps:
            - name: {{ .Values.Step1.name }}
        execution:
          onStart:
            # sed -i "s/docker.artifactory/docker.artifactory-unified.soleng-us.jfrog.team/" $res_PetClinicGitRepo_resourcePath/{{ .Values.GitRepo.path }}/Dockerfile
          onComplete:
            - echo $step_env_var2
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
      
      - name: {{ .Values.Step3.name }}
        type: DockerPush
        configuration:
          affinityGroup: bldGroup
          targetRepository: docker
          forceXrayScan: false
          failOnScan: false
          autoPublishBuildInfo: true
          integrations:
            - name: {{ .Values.Artifactory }}
          inputSteps:
            - name: {{ .Values.Step2.name }}
          outputResources:
            - name: {{ .Values.Step3.outputResourceName }}
