Resource1 :
  name : 
  imageName : ImageName
Resource2 :
  name : appl_build_info
  imageName : ImageName
be_gitRepo :
  name : Name for for Github repo
  gitProvider : GitRepo
  path: 
  branch : Branch name if any
Artifactory: ARTFY_INT
Pipelines:
  name: demo-template-pipeline
GitRepo:
  name: GITHUB_RT
  path: Path to your maven source code
Step1 :
  name: step1
Step2 :
  name: step2Name
  dockerFileLocation: docfileLocation
  dockerImageName: vjnpipelines.jfrog.io/docker-template-local/app
  outputResourceName: DockerImageBuildInfoName
Step3 :
  name: step3Name
  outputResourceName : DockerImagePublishedBuildInfo
